#!/bin/bash

# terminal
term=(
zsh
python
vim
tmux
htop
ranger
imagemagick
ffmpeg
exiftool
yt-dlp
newsboat
hledger
fzf
gnu-sed
gnupg
gnu-units
coreutils
wireguard-tools
rclone
rsync
aerc
w3m
)

# essential
ess=(
firefox
kitty
stats
telegram
vlc
homebrew/cask/mpv
spotify
transmission
keepassxc
#utils
the-unarchiver
appcleaner
amorphousdiskmark
balenaetcher
tor-browser
)

brew install ${term[@]} ${ess[@]} 
#echo "what to install"
#select choice in all ess term quit
#do 
#    echo "selected is $choice"
#    case $choice in 
#        all)
#            brew install ${term[@]} ${ess[@]} 
#            break
#            ;;
#        ess)
#            brew install ${ess[@]}
#            break
#            ;;
#        term)
#            brew install ${term[@]}
#            break
#            ;;
#        quit)
#            break
#            ;;
#        *)
#            echo "invalid"
#            ;;
#    esac
#done

