#!/bin/bash

export VISUAL=vim;
export EDITOR=vim;


export GPG_TTY=$(tty)

# aliases
alias duf='xdg-open `fzf`'
alias vuf='vim `fzf`'

alias hist='history 0 | fzf'

alias q='exit'
alias la='ls -alh --color'
alias rn='. ranger'
alias nb='newsboat'
alias hl='hledger'

alias y4='yt-dlp --add-metadata -f mp4 -c' #video in mp4
alias y4a='yt-dlp --add-metadata -xc' #audio only
alias y4e='yt-dlp --add-metadata --write-thumbnail bestvideo -c'

#scripts dir
export PATH=$PATH:~/00files/dot_files/scripts
export PATH=$PATH:~/.local/bin

#macos gnu
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/gnu-units/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"

#xdg
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}

#xdg
export LESSHISTFILE=-

