#!/bin/bash

export VISUAL=vim;
export EDITOR=vim;


export GPG_TTY=$(tty)

# aliases
alias duf='xdg-open `fzf`'
alias vuf='vim `fzf`'

alias hist='history 0 | fzf'

alias q='exit'
alias la='ls -alh'
alias rn='. ranger'
alias nb='newsboat'
alias hl='hledger'

alias y4='yt-dlp --add-metadata -f mp4 -c' #video in mp4
alias y4a='yt-dlp --add-metadata -xc' #audio only
alias y4e='yt-dlp --add-metadata --write-thumbnail bestvideo -c'

# OS specific
case "$(uname -s)" in
    
    Darwin)
        alias ls='ls -G' # ls color for macos

        ;;
    Linux)
        alias ls='ls --color' # ls color for linux

        ;;
    *)
        #other os
        ;;
esac

#scripts dir
export PATH=$PATH:~/00files/dot_files/scripts
export PATH=$PATH:~/.local/bin
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
