#!/usr/bin/env bash

#remove existing files
rm -rf ~/.config ~/.vimrc ~/.vim ~/.bashrc ~/.bash_profile

#vim
ln -s ~/00files/dot_files/.vimrc ~/.vimrc
ln -s ~/00files/dot_files/.vim ~/.vim

#bash
ln -s ~/00files/dot_files/.bashrc ~/.bashrc
ln -s ~/00files/dot_files/.bash_profile ~/.bash_profile

#zsh

#.config
ln -s ~/00files/dot_files/.config ~/.config

./formac/brew
./formac/browser
./formac/macos

echo "*********************************"
echo "*********************************"
echo "*********************************"
echo "*********************************"
echo "*********************************"
echo "update git user and email"
