#!/usr/bin/env bash

case "$(uname -s)" in
    
    Darwin)
        #remove configs
        rm -rf ~/.config/*

        #make symbolic link for configs
#        ln -s ~/00files/dot_files/config/karabiner ~/.config/karabiner

        #install apps    
        ./formac/macos
        ./formac/brew

        ;;
    Linux)
        #remove configs 
        rm -rf ~/.config/i3 \
        ~/.config/polybar \
        ~/.config/fcitx \
        
        #make symbolic link for configs

        ln -s ~/00files/dot_files/config/i3 ~/.config/i3
        ln -s ~/00files/dot_files/config/polybar ~/.config/polybar
        ln -s ~/00files/dot_files/config/fcitx ~/.config/fcitx

        ;;
    *)
        #other os
        ;;
esac

#remove configs
rm -rf ~/.vimrc \
~/.vim \
~/.viminfo \
~/.bashrc \
~/.bash_profile \
~/.bash_history \
~/.bash_logout \
~/.tmux.conf \
~/.zshrc \
~/.zshenv \
~/.zcompdump \
~/.zsh_history \
~/.lesshst\
~/.profile\

rm -rf ~/.config/htop \
~/.config/mpv \
~/.config/ranger \
~/.config/tmux \
~/.config/newsboat ~/.newsboat \
~/.config/aerc \

#make symbolic links

ln -s ~/00files/dot_files/config/htop ~/.config/htop
ln -s ~/00files/dot_files/config/mpv ~/.config/mpv
ln -s ~/00files/dot_files/config/ranger ~/.config/ranger
ln -s ~/00files/dot_files/config/tmux ~/.config/tmux
ln -s ~/00files/dot_files/config/newsboat ~/.config/newsboat
ln -s ~/00files/dot_files/config/kitty ~/.config/kitty

if [ ! -d "${HOME}/.config/aerc" ]; then
    mkdir -p ~/.config/aerc
fi
ln -s ~/00files/dot_files/config/aerc/aerc.conf ~/.config/aerc/aerc.conf
ln -s ~/00files/dot_files/config/aerc/binds.conf ~/.config/aerc/binds.conf

#vim
ln -s ~/00files/dot_files/config/vim ~/.config/vim

if [ ! -d "${HOME}/.config/vim/undodir" ]; then
    mkdir -p ~/.config/vim/undodir
fi

#bash
ln -s ~/00files/dot_files/home/.bashrc ~/.bashrc
ln -s ~/00files/dot_files/home/.bash_profile ~/.bash_profile

#zsh
ln -s ~/00files/dot_files/home/.zshenv ~/.zshenv
ln -s ~/00files/dot_files/config/zsh ~/.config/zsh

if [ ! -d "${HOME}/00files/local/en-vars" ]; then
  mkdir -p "${HOME}/00files/local";
  touch "${HOME}/00files/local/en-vars";
fi

#zsh plugins
zshdirplug="${HOME}/00files/dot_files/config/zsh/zsh-plugins/zsh-syntax-highlighting"

if [ -d "$zshdirplug" ]; then
  echo "zshplugins already exist"
else
  mkdir -p "zsh-plugins";
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $zshdirplug
fi

mkdir -p ~/.config/git
#other
echo "*********************************"
echo "*********************************"
echo "*********************************"
echo "*********************************"
echo "*********************************"
echo "update git user and email"
echo "at ~/.config/git/config"

