#!/usr/bin/env bash

#remove existing files
rm -rf ~/.config ~/.vimrc ~/.vim ~/.bashrc ~/.zshrc ~/.bash_profile ~/.scripts

#vim
ln -s ~/00files/dot_files/.vimrc ~/.vimrc
ln -s ~/00files/dot_files/.vim ~/.vim

#bash
ln -s ~/00files/dot_files/.bashrc ~/.bashrc
ln -s ~/00files/dot_files/.bash_profile ~/.bash_profile

#zsh
ln -s ~/00files/dot_files/.zshrc ~/.zshrc

#.config
ln -s ~/00files/dot_files/.config ~/.config

./formac/brew
./formac/browser
./formac/macos

#zsh plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting zsh-plugins/

echo "*********************************"
echo "*********************************"
echo "*********************************"
echo "*********************************"
echo "*********************************"
echo "update git user and email"
