#!/usr/bin/env bash

case "$(uname -s)" in
    
    Darwin)
        #remove configs
        rm -rf ~/.config/*

        #make symbolic link for configs
#        ln -s ~/00files/dot_files/config/karabiner ~/.config/karabiner

        #install apps    
        ./formac/macos
        ./formac/brew

        ;;
    Linux)
        #remove configs 
        rm -rf ~/.config/i3 \
        ~/.config/polybar \
        ~/.config/fcitx \
        ~/.config/kitty \

        
        #make symbolic link for configs

        ln -s ~/00files/dot_files/config/i3 ~/.config/i3
        ln -s ~/00files/dot_files/config/polybar ~/.config/polybar
        ln -s ~/00files/dot_files/config/fcitx ~/.config/fcitx

        ;;
    *)
        #other os
        ;;
esac

#remove configs
rm -rf ~/.vimrc \
~/.vim \
~/.viminfo \
~/.bashrc \
~/.bash_profile \
~/.bash_history \
~/.tmux.conf \
~/.zshrc \
~/.zcompdump \
~/.zsh_history \

rm -rf ~/.config/newsboat ~/.newsboat

#make symbolic links
rm -rf ~/.config/htop \
~/.config/mpv \
~/.config/ranger \
~/.config/tmux \

ln -s ~/00files/dot_files/config/htop ~/.config/htop
ln -s ~/00files/dot_files/config/mpv ~/.config/mpv
ln -s ~/00files/dot_files/config/ranger ~/.config/ranger
ln -s ~/00files/dot_files/config/tmux ~/.config/tmux
ln -s ~/00files/dot_files/config/newsboat ~/.config/newsboat

#vim
if [ ! -d "${HOME}/.vim/undodir" ]; then
    mkdir -p ~/.vim/undodir
fi
ln -s ~/00files/dot_files/home/.vim/vimrc ~/.vim/vimrc
ln -s ~/00files/dot_files/home/.vim/colors ~/.vim/colors

#bash
ln -s ~/00files/dot_files/home/.bashrc ~/.bashrc
ln -s ~/00files/dot_files/home/.bash_profile ~/.bash_profile

#zsh
ln -s ~/00files/dot_files/home/.zshrc ~/.zshrc

if [ ! -d "${HOME}/00files/local/en-vars" ]; then
  mkdir -p "${HOME}/00files/local";
  touch "${HOME}/00files/local/en-vars";
fi

#zsh plugins
if [ ! -d "zsh-plugins" ]; then
  mkdir -p "zsh-plugins";
fi

mkdir -p ~/00files/dot_files/zsh-plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting zsh-plugins/zsh-syntax-highlighting

mkdir -p ~/.config/git
#other
echo "*********************************"
echo "*********************************"
echo "*********************************"
echo "*********************************"
echo "*********************************"
echo "update git user and email"
echo "at ~/.config/git/config
