syntax on

set noerrorbells
"tabs to spaces
set tabstop=2 
set softtabstop=2
set shiftwidth=2
"convert tabs to spaces
set expandtab

set backspace=indent,eol,start

" line nums
set nu rnu
set colorcolumn=79

" backup
set noswapfile nobackup

" search
set is ic hls

" status bar
set laststatus=2 ruler showcmd

" use system clipboard
set clipboard=unnamedplus "for linux

" autocomplition
set wildmenu

" highlight curren line
"set cuc cul

set scrolloff=8 "stop at 8 lines before end when scrolling

set undodir=~/.config/vim/undodir"
set undofile

set viminfo+=n~/.cache/viminfo

colorscheme gruvbox
set background=dark
set t_Co=256
set t_ut=

" ---- Keymaps ----
let mapleader = " " 

nnoremap <Leader>f :%s//g<Left><Left>
nnoremap <Leader>d :put =strftime('%Y-%m-%d-%H-%M')<CR>
nnoremap <Leader>g :-1put =expand('%:P')<CR>I# <esc>$xxx:put =strftime('%Y-%m-%d-%H-%M')<CR>IDate: <esc>oSource: <CR>[LINK1]()<Left>

"change clipboard to mac
nnoremap <Leader>p :set clipboard=unnamed<CR> 

