#!/bin/bash

rsync -aP --delete /Volumes/4tb-exfat/01-movies/ /Volumes/2tb-movies/01-movies/

rsync -aP --delete /Volumes/4tb-exfat/00-backup/ /Volumes/2tb-data/00-backup/
rsync -aP --delete /Volumes/4tb-exfat/02-prod/ /Volumes/2tb-data/02-prod/
rsync -aP --delete /Volumes/4tb-exfat/03-PP/ /Volumes/2tb-data/03-PP/
rsync -aP --delete /Volumes/4tb-exfat/08-p-pc/ /Volumes/2tb-data/08-p-pc/
rsync -aP --delete /Volumes/4tb-exfat/09-db/ /Volumes/2tb-data/09-db/
rsync -aP --exclude='*.mkv' --exclude='*.mp4' --exclude='*.m4v' /Volumes/4tb-exfat/01-movies/ /Volumes/2tb-data/01-movies/

rsync -aP --delete /Volumes/4tb-exfat/00-backup/ /Volumes/500gb-hfs/00-backup/
rsync -aP --delete /Volumes/4tb-exfat/02-prod/ /Volumes/500gb-hfs/02-prod/
rsync -aP --delete --exclude='*.mkv' --exclude='*.mp4' --exclude='*.m4v' /Volumes/4tb-exfat/01-movies/ /Volumes/500gb-hfs/01-movies/


