#!/bin/bash

copyfromdir="/Volumes/4tb-exfat"
copyto1dir="/Volumes/2tb-data"
copyto2dir="/Volumes/2tb-media"

MEDIAEXCLUDE=(
  "*.mkv"
  "*.mp4"
  "*.avi"
  "*.m4v"
)

#bash delete_hidden $copyfromdir

case "$(uname -s)" in
    
    Darwin)
        
        echo "--- copy data ---" 
        rsync -aP --delete --exclude="._*" "$copyfromdir/00-backup/" "$copyto1dir/00-backup/"
        rsync -aP --delete --exclude="._*" "$copyfromdir/02-prod/" "$copyto1dir/02-prod/"
        rsync -aP --delete --exclude="._*" "$copyfromdir/03-PP/" "$copyto1dir/03-PP/"
        rsync -aP --delete --exclude="._*" "$copyfromdir/08-p-pc/" "$copyto1dir/08-p-pc/"
        rsync -aP --delete --exclude="._*" "$copyfromdir/09-db/" "$copyto1dir/09-db/"

        echo "--- copy partial media ---"
        rsync -aP "${MEDIAEXCLUDE[@]/#/--exclude=}" "$copyfromdir/01-media/" "$copyto1dir/01-media/"
        
        echo "--- copy media ---"
        rsync -aP --delete --exclude="._*" "$copyfromdir/01-media/" "$copyto2dir/01-media/"

        ;;
    Linux)

        ;;
    *)
        #other os
        ;;
esac

