#!/bin/bash

dirpath="/Volumes/data"

HIDDENEXCLUDE=(
  "._*"
  ".DS_Store"
)

case "$(uname -s)" in
    
    Darwin)

        rsync -avP --delete "${HIDDENEXCLUDE[@]/#/--exclude=}" "$dirpath/00-backup/DBX/" "~/00files/Dropbox/"
        rsync -avP --delete "${HIDDENEXCLUDE[@]/#/--exclude=}" "$dirpath/00-backup/NCED/" "~/00files/NCED/"
        rsync -avP --delete "${HIDDENEXCLUDE[@]/#/--exclude=}" "$dirpath/00-backup/local/" "~/00files/local/"
        ;;
    Linux)
        ;;
    *)
        #other os
        ;;
esac
