#!/bin/bash

set -e
workdir=$CLIPS

case "$(uname -s)" in
    
    Darwin)
        upaste='pbpaste'
        ucopy='pbcopy'
        ;;
    Linux)
        upaste='wl-paste'
        ucopy='wl-copy'
        ;;
    *)
        
        ;;
esac

main() {
    echo -e "new-bookmark\n$(cat $workdir)" > $workdir
    echo -e "delete-bookmark\n$(cat $workdir)" > $workdir
    echo -e "edit-file\n$(cat $workdir)" > $workdir
    thelink=$(cat $workdir | fzf)
    
    if [ "$thelink" == "new-bookmark" ] ; then
        newitem ""
    elif [ "$thelink" == "delete-bookmark" ] ; then
        deleteitem ""
    elif [ "$thelink" == "edit-file" ] ; then
        $EDITOR $workdir
    else
        copyitem ""
    fi
}


function newitem() {
    read -p "name: " linkname 
    toput=$($upaste)
    echo "$linkname $toput" >> $workdir
}

function copyitem() {
    neolink=$(echo $thelink | awk '{print $NF}')
    echo $neolink | $ucopy 
}

function deleteitem() {
    read -p "DELETE-MODE"
    todelete=$(cat $workdir | fzf)
    todelete=$(echo $todelete | awk '{print $1" "$2" "$3}')
    sed -i "/$todelete/d" $workdir
}

trap cleanup EXIT INT TERM

function cleanup() {
    sed -i '1d' $workdir
    sed -i '1d' $workdir
    sed -i '1d' $workdir
}

main ""
