#!/bin/bash
if [ ! -d "done" ]; then
  mkdir -p "done";
fi
for f in *.{mp4,MP4,mov,MOV,avi,AVI,webm,WEBM,mkv,MKV,3gp,mts,mpg,m4v,M4V}; do ffmpeg -i "$f" -c:v libx265 -vtag hvc1 -crf 21 "done/${f%.*}.mp4"; done
