#!/bin/bash

for d in */ ; do
    convert $d*.{png,jpg,jpeg,PNG,JPG,JPEG} -density 600 -colorspace sRGB ${d%/}.pdf
done

for f in */*/ ; do
    ff=${f//\//-}
    convert $f*.{png,jpg,jpeg,PNG,JPG,JPEG} -density 600 -colorspace sRGB ${ff%?}.pdf
done
#(pwd | grep -o '[^/]*$')
