#!/bin/bash

workdir=$INFDIR

case "$(uname -s)" in

    Darwin)
        upaste='pbpaste'
        ucopy='pbcopy'
        ;;
    Linux)
        upaste='wl-paste'
        ucopy='wl-copy'
        ;;
    *)

        ;;
esac


cat $workdir | fzf | awk '{$1="";print}' | sed -r 's/^.{1}//' | $ucopy
