#!/bin/bash

echo "------Syncing Dropbox--------"
echo "-----------------------------"
rclone sync -v dbx: ~/00files/Dropbox --exclude ".DS_Store" --exclude "._*"
echo "------Syncing Nextcloud------"
echo "-----------------------------"
rclone sync -v nced: ~/00files/NCED --exclude ".DS_Store" --exclude "._*"
